# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FrkhcZa1DIFpNvO4iT48KS63WU3-THpp
"""

#comment

print("\n1\n")
print("Hello World")
if 5>2:
  print("Five is greater than two")

# Variable data type

print("\n2\n")
#x = "University of portsmouth"
x = 'University of portsmouth'
X = str(10)
y = int(5)
z = float(7)
print(X, x ,y ,z )
print(type(x))
print(type(y))
print(type(z))

#variable declaration types

print("\n3\n")
myname = 'Nikita'
my_no = '123456789'
_my_uni = 'uop'
my_address = 'portsmouth'
mycountry = 'UK'
MYORIGIN = 'india'

print(myname)
print(my_no)
print(_my_uni)
print(my_address)
print(mycountry)
print(MYORIGIN)

#multiple values assign

print("\n4\n")
country = "India","UK","Germany"
x,y,z = country
print(x + y + z )

#basic Maths operation
print("\n5\n")
a = 5
b = 6
print(a+b)
print(a-b)
print(a/b)
print(a*b)

#function define

print("\n6\n")

X = "India" #variable created outside of a function
def myfunc():
  global X #used by both inside and outside funtion
  X = "UK"
  print ("i love "+ X)

myfunc()

print ("* i love "+ X)